### ISSUE TITLE
implementar {waiter} para pantallas de espera en carga

### ISSUE THREAD

**Issue by jpruiznicolini** [dnme-minturdep/turismo_internacional#15]
**Documentación:** https://github.com/JohnCoene/waiter

Cc: @eliansoutu

**Comment by eliansoutu** [comment]
Ahí estuve probando el `waiter` en el repo de conectividad, con un texto + logo del Minturdep (estático):
![image](https://user-images.githubusercontent.com/62449092/158665928-50405ece-8f80-4223-807e-5886b30003cd.png)

Otra opción es usar algunas de las plantillas (dinámicas) que trae el paquete, por ejemplo:
![image](https://user-images.githubusercontent.com/62449092/158667278-38d0827d-2858-47a3-922e-6920ddc604c6.png)

Cómo lo ven?

**Comment by TuQmano** [comment]
vamos con logo version
